# Generated by Django 4.2.20 on 2025-06-06 10:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('complaints', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaintcategory',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='complaintcategory',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='complaint',
            name='attachments',
            field=models.FileField(blank=True, help_text='Attach relevant files (e.g., photos, documents).', null=True, upload_to='complaints_attachments/'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='email',
            field=models.EmailField(blank=True, help_text='Email address of the submitter (for anonymous or guest submissions).', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='full_name',
            field=models.CharField(blank=True, help_text='Full name of the submitter (for anonymous or guest submissions).', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='location_address',
            field=models.CharField(blank=True, help_text='Specific address or location related to the complaint.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Phone number of the submitter (for anonymous or guest submissions).', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='complaintupdate',
            name='new_assigned_to',
            field=models.ForeignKey(blank=True, help_text='New user assigned to the complaint.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='new_assigned_updates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='complaintupdate',
            name='new_priority',
            field=models.CharField(blank=True, choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], help_text='New priority if the update was a priority change.', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='complaintupdate',
            name='new_status',
            field=models.CharField(blank=True, choices=[('new', 'New'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('closed', 'Closed'), ('reopened', 'Reopened')], help_text='New status if the update was a status change.', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='complaintupdate',
            name='old_assigned_to',
            field=models.ForeignKey(blank=True, help_text='Previous user assigned to the complaint.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='old_assigned_updates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='complaintupdate',
            name='old_priority',
            field=models.CharField(blank=True, choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], help_text='Old priority if the update was a priority change.', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='complaintupdate',
            name='old_status',
            field=models.CharField(blank=True, choices=[('new', 'New'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('closed', 'Closed'), ('reopened', 'Reopened')], help_text='Old status if the update was a status change.', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='complaintupdate',
            name='update_type',
            field=models.CharField(choices=[('comment', 'Comment'), ('status_change', 'Status Change'), ('assignment_change', 'Assignment Change'), ('priority_change', 'Priority Change'), ('resolution', 'Resolution')], default='comment', help_text='Type of update (e.g., comment, status change, assignment change).', max_length=20),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='assigned_to',
            field=models.ForeignKey(blank=True, help_text='Staff member or admin assigned to handle this complaint.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='complaints_assigned', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='category',
            field=models.ForeignKey(blank=True, help_text='The category this complaint belongs to.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='complaints', to='complaints.complaintcategory'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='The date and time when this object was first created.', verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='description',
            field=models.TextField(help_text='Detailed description of the complaint, including all relevant information.'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', help_text='Priority level of the complaint (e.g., for staff action).', max_length=20),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='resolution_details',
            field=models.TextField(blank=True, help_text='Details regarding how the complaint was resolved.', null=True),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='resolved_at',
            field=models.DateTimeField(blank=True, help_text='The date and time the complaint was marked as resolved.', null=True),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('closed', 'Closed'), ('reopened', 'Reopened')], default='new', help_text='Current status of the complaint.', max_length=20),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='subject',
            field=models.CharField(help_text='A brief summary or title of the complaint.', max_length=255),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='submitted_by',
            field=models.ForeignKey(blank=True, help_text='Authenticated user who submitted the complaint (if any).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='complaints_submitted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='The date and time when this object was last updated.', verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='complaintcategory',
            name='description',
            field=models.TextField(blank=True, help_text="A brief description of this category, e.g., 'Issues related to campus infrastructure.'", null=True),
        ),
        migrations.AlterField(
            model_name='complaintupdate',
            name='complaint',
            field=models.ForeignKey(help_text='The complaint to which this update applies.', on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='complaints.complaint'),
        ),
        migrations.AlterField(
            model_name='complaintupdate',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='The date and time when this object was first created.', verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='complaintupdate',
            name='is_public',
            field=models.BooleanField(default=False, help_text="If checked, this update will be visible to the complaint's original submitter."),
        ),
        migrations.AlterField(
            model_name='complaintupdate',
            name='message',
            field=models.TextField(blank=True, help_text='Detailed message or comment about the update.'),
        ),
        migrations.AlterField(
            model_name='complaintupdate',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='The date and time when this object was last updated.', verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='complaintupdate',
            name='updated_by',
            field=models.ForeignKey(blank=True, help_text='The user (admin/staff) who made this update.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='complaint_updates_made', to=settings.AUTH_USER_MODEL),
        ),
    ]
