# Generated by Django 5.2.2 on 2025-06-28 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaint',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='complaint',
            name='location_address',
        ),
        migrations.RemoveField(
            model_name='complaint',
            name='longitude',
        ),
        migrations.DeleteModel(
            name='ComplaintUpdate',
        ),
    ]
