# Generated by Django 5.2.2 on 2025-07-05 11:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FAQCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the FAQ category (e.g., Complaint, Services)', max_length=100, unique=True)),
                ('order', models.IntegerField(default=0, help_text='Order in which categories should appear (lower number first)')),
            ],
            options={
                'verbose_name': 'FAQ Category',
                'verbose_name_plural': 'FAQ Categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='FAQItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(help_text='The frequently asked question', max_length=255)),
                ('answer', models.TextField(help_text='The detailed answer to the question')),
                ('is_published', models.BooleanField(default=True, help_text='Whether this FAQ item should be visible on the website')),
                ('order', models.IntegerField(default=0, help_text='Order in which FAQ items should appear within their category (lower number first)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(help_text='The category this FAQ item belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='faq_items', to='faqs.faqcategory')),
            ],
            options={
                'verbose_name': 'FAQ Item',
                'verbose_name_plural': 'FAQ Items',
                'ordering': ['category__order', 'category__name', 'order', 'question'],
                'unique_together': {('category', 'question')},
            },
        ),
    ]
