# Generated by Django 5.2.2 on 2025-06-28 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OverdueNotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(max_length=50)),
                ('request_id', models.IntegerField()),
                ('notified_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-notified_at'],
                'unique_together': {('request_type', 'request_id')},
            },
        ),
    ]
