# Generated by Django 5.2.2 on 2025-06-28 08:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InquiryCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text="'A brief of your inquiry.'", null=True)),
            ],
            options={
                'verbose_name': 'Inquiry Category',
                'verbose_name_plural': 'Inquiry Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, help_text='Full name of the submitter (for anonymous or guest submissions).', max_length=255, null=True)),
                ('email', models.EmailField(blank=True, help_text='Email address of the submitter (for anonymous or guest submissions).', max_length=254, null=True)),
                ('phone_number', models.CharField(blank=True, help_text='Phone number of the submitter (for anonymous or guest submissions).', max_length=20, null=True)),
                ('subject', models.CharField(help_text='A brief summary or title of inquiry.', max_length=255)),
                ('description', models.TextField()),
                ('answer', models.TextField(blank=True, null=True)),
                ('attachments', models.FileField(blank=True, help_text='Attach relevant files (e.g., photos, documents).', null=True, upload_to='inquiry_attachments/')),
                ('status', models.CharField(choices=[('new', 'New'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('closed', 'Closed'), ('rejected', 'Rejected')], default='new', max_length=20)),
                ('resolution_details', models.TextField(blank=True, help_text='Details regarding how the inquiry was resolved.', null=True)),
                ('resolved_at', models.DateTimeField(blank=True, help_text='The date and time the inquiry was marked as resolved.', null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('request_type_slug', models.CharField(default='inquiry', editable=False, max_length=50)),
                ('assigned_to', models.ForeignKey(blank=True, help_text='Admin/Staff member assigned to this inquiry.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inquiries_assigned', to=settings.AUTH_USER_MODEL)),
                ('submitted_by', models.ForeignKey(blank=True, help_text='Authenticated user who submitted the complaint (if any).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inquiries_submitted', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inquiries', to='inquiries.inquirycategory')),
            ],
            options={
                'verbose_name': 'Inquiry',
                'verbose_name_plural': 'Inquiries',
                'ordering': ['-submitted_at'],
            },
        ),
    ]
