# Generated by Django 4.2.20 on 2025-06-06 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inquiries', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inquiry',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='The date and time when this object was first created.', verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='The date and time when this object was last updated.', verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='inquirycategory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='The date and time when this object was first created.', verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='inquirycategory',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='The date and time when this object was last updated.', verbose_name='Updated At'),
        ),
    ]
