# Generated by Django 5.2.2 on 2025-06-28 08:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmergencyType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Emergency Type',
                'verbose_name_plural': 'Emergency Types',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='EmergencyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, help_text='Full name of the submitter (for anonymous or guest submissions).', max_length=255, null=True)),
                ('email', models.EmailField(blank=True, help_text='Email address of the submitter (for anonymous or guest submissions).', max_length=254, null=True)),
                ('phone_number', models.CharField(blank=True, help_text='Phone number of the submitter (for anonymous or guest submissions).', max_length=20, null=True)),
                ('subject', models.CharField(help_text='A brief summary or title of the complaint.', max_length=255)),
                ('attachments', models.FileField(blank=True, help_text='Attach relevant files (e.g., photos, documents).', null=True, upload_to='emergency_attachments/')),
                ('location', models.CharField(help_text='Specific location of the emergency.', max_length=255)),
                ('description', models.TextField(help_text='Details of the emergency.')),
                ('status', models.CharField(choices=[('new', 'New'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('closed', 'Closed'), ('rejected', 'Rejected')], default='new', max_length=20)),
                ('action_taken', models.TextField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('request_type_slug', models.CharField(default='emergency', editable=False, max_length=50)),
                ('assigned_to', models.ForeignKey(blank=True, help_text='Admin/Staff member assigned to this service request.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emergency_requests_assigned', to=settings.AUTH_USER_MODEL)),
                ('responder', models.ForeignKey(blank=True, help_text='Staff member who responded to the emergency.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emergency_reports_responded', to=settings.AUTH_USER_MODEL)),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='emergency_reports_submitted', to=settings.AUTH_USER_MODEL)),
                ('emergency_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emergency_reports', to='emergencies.emergencytype')),
            ],
            options={
                'verbose_name': 'Emergency Report',
                'verbose_name_plural': 'Emergency Reports',
                'ordering': ['-submitted_at'],
            },
        ),
    ]
