# Generated by Django 4.2.20 on 2025-06-05 11:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmergencyType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The date and time when this object was first created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='The date and time when this object was last updated.')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Emergency Type',
                'verbose_name_plural': 'Emergency Types',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='EmergencyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The date and time when this object was first created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='The date and time when this object was last updated.')),
                ('location', models.CharField(help_text='Specific location of the emergency.', max_length=255)),
                ('description', models.TextField(help_text='Details of the emergency.')),
                ('status', models.CharField(choices=[('new', 'New'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='new', max_length=20)),
                ('action_taken', models.TextField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('emergency_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emergency_reports', to='emergencies.emergencytype')),
                ('responder', models.ForeignKey(blank=True, help_text='Staff member who responded to the emergency.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emergency_reports_responded', to=settings.AUTH_USER_MODEL)),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emergency_reports_submitted', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Emergency Report',
                'verbose_name_plural': 'Emergency Reports',
                'ordering': ['-created_at'],
            },
        ),
    ]
