# Generated by Django 4.2.20 on 2025-06-05 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('student', 'Student'), ('parent', 'Parent'), ('staff', 'Staff'), ('guest', 'Guest')], default='student', max_length=10),
        ),
    ]
